### ISSUE TITLE
Wyszukaj pracownika; Filtr; Pozycja; b.d. - W3

### ISSUE THREAD

**Issue by wyspiansky** [Code-Poets/polish-lody#1]
Dotyczy: Wyszukiwanie pracownika 
Nie ma możliwości ustawienia filtra pracowników, dla których "Pozycja" ma wartość "b.d."
Może to skutkować trudnością odnalezienia pracowników dla których "Pozycja" nie została określona podczas rejestracji.
Przykład:
Podczas przeglądu większej bazy pracowników poważnie utrudnione wyszukanie pracowników, dla których nie zostało uzupełnione pole "Pozycja"
Sugerowane rozwiązanie: 
1) W przypadku braku wyboru w polu "Pozycja" ustawić standardową wartość np. "Inne"
2) W tabeli pracowników dodać strzałki sortowania przy pozycji "Pozycja"

**Comment by Jakub89** [comment]
Rozwiązane sposobem nr1
