### ISSUE TITLE
Employee list; Employee detail; Add Month; Rate per hour - High

### ISSUE THREAD

**Issue by wyspiansky** [Code-Poets/polish-lody#11]
When employee has Rate per hour set for example 13,35 when you press Add Month and click Submit button you get error message that you can only type one number after comma.
In English version of site the error message is in Polish instead of English.
![2017-04-21 15_41_21-create new month _ polish lody](https://cloud.githubusercontent.com/assets/27853786/25280107/12e958fc-26a9-11e7-8a33-a56f4263a312.png)

**Comment by Jakub89** [comment]
Popup-y ["przeglądarkowe"](https://www.tjvantoll.com/2012/08/05/html5-form-validation-showing-all-error-messages/), ich język zależy od języka ustawionego w Twojej przeglądarce, popup-y zrobione przez nas powinny być potłumaczone.

Rozszerzyłem możliwość wpisywania miejsc po przecinku do 2, co ma nieco więcej sensu, skoro mowa o walucie.
