### ISSUE TITLE
Employee list; Employee detail; Add Month; Adding the same month - Low

### ISSUE THREAD

**Issue by wyspiansky** [Code-Poets/polish-lody#14]
When trying to add month that already exists, nothing happens but there is no error message. Might be confusing for the user.

**Comment by Jakub89** [comment]
Zazwyczaj ten błąd jest wyłapywany przez funkcje ajax-ową, ale rzeczywiście był taki problem w jednym przypadku i na dodatek tylko w wersji polskie. Naprawione.
