### ISSUE TITLE
Nowy pracownik;  Imię Nazwisko - W3

### ISSUE THREAD

**Issue by wyspiansky** [Code-Poets/polish-lody#6]
1) Podczas zakładania konta możliwość wpisania cyfr w polu Imię oraz Nazwisko
2) Pola powinny automatycznie zmieniać pierwszą literę Imienia oraz Nazwiska z małej na dużą, żeby uniknąć braku konsekwencji we wpisywaniu (poprawi to czytelność danych)

**Comment by Jakub89** [comment]
Zrobione
