### ISSUE TITLE
New employee; Rate per hour - Low

### ISSUE THREAD

**Issue by wyspiansky** [Code-Poets/polish-lody#9]
When creating new employee and typing wrong length of numbers in Rate per hour field, the error message is not specific about what field it is about:
It's:
Ensure that there are no more than 7 digits in total.
Ensure that there are no more than 5 digits before the decimal point.
Should be like:
Ensure that in Rate per hour field, there are no more than 7 digits in total.

**Comment by Jakub89** [comment]
Zamieniłem żeby popup-y przeglądarki pojawiały się przed tymi errorami djangowymi, według mnie są bardziej precyzyjne i nie trzeba czekać na przeładowanie strony.
